version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cocktail-gacha-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - cocktail-gacha-{{ .Branch }}
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - save_cache:
          key: cocktail-gacha-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - public

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cocktail-gacha-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - cocktail-gacha-{{ .Branch }}
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: test
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install now
          command: sudo yarn global add now
      - run:
          name: deplooy
          command: now -t ${NOW_TOKEN}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
